# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dreambuy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreambuy', '0005_userbids_bid_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='lucky_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(default=dreambuy.models.prdtcode, max_length=50)),
                ('Product_name', models.CharField(max_length=250)),
                ('winner_userid', models.IntegerField(default=1)),
                ('time', models.CharField(max_length=250)),
                ('winner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_sold',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_winner',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_winner_id',
            field=models.IntegerField(default=1),
        ),
    ]
