# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0006_auto_20171030_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='AWS_affliate_link',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AddField(
            model_name='product',
            name='AWS_percent',
            field=models.IntegerField(default=1),
        ),
    ]
